#!/bin/bash

PREDEFINED=""
GENERATE_ASSEMBLER=0
GENERATE_SYMBOL_TABLE=0
INPUT=""
OUTPUT=""
ERR=0

function usage() {
    echo "usage: mcc [-h] [-s] [-S] FILE"
    echo "-h       Print this help message and exit"
    echo "-s       Generate symbol table"
    echo "-S       Generate assembler output"
    echo "-p FILE  Specify alternate location of predefined classes file"
}

# parse arguments

OPTERR=0
OPTARGS=":sSp:o:h"

if [[ $# -eq 0 ]];
then
    usage
    exit 1
fi

while getopts $OPTARGS opt; do
    case $opt in
    h)
    usage
    exit 1
    ;;
    p)
    PREDEFINED="$OPTARG"
    ;;
    S)
    GENERATE_ASSEMBLER=1
    ;;
    s)
    GENERATE_SYMBOL_TABLE=1
    ;;
    \?)
    echo "Invalid switch option '$OPTARG'" >&2
    ERR=1
    ;;
    :)
    echo "Missing parameter to switch '$OPTARG'" >&2
    ERR=1
    ;;
    esac
done

if [[ $ERR -ne 0 || $OPTIND -gt $# ]];
then
    usage
    exit 1
fi

# last argument is INPUT

shift $((OPTIND-1))
INPUT="$1"

# ensure INPUT exists, isn't a directory and is readable

if [[ ! -e $INPUT ]];
then
    echo "$INPUT: No such file or directory"
    exit 1
fi

if [[ -d $INPUT ]];
then
    echo "$INPUT: Is a directory"
    exit 1
fi

if [[ ! -r $INPUT ]];
then
    echo "$INPUT: Permission denied"
    exit 1
fi

# dump compiler output to TEMP

TEMP=/tmp/mate-$RANDOM

if [ "$PREDEFINED" != "" ];
then
    mc -p "$PREDEFINED" < $INPUT > $TEMP
    RETVAL=$?
else
    mc < $INPUT > $TEMP
    RETVAL=$?
fi

# abort if compile stage failed

if [[ $RETVAL -ne 0 ]];
then
    rm -rf $TEMP > /dev/null 2>&1
    exit 1
fi

# don't assemble, just copy assembler to OUTPUT file and exit success

if [[ $GENERATE_ASSEMBLER -ne 0 ]];
then
    OUTPUT=${INPUT%%.m}.s
    cp $TEMP $OUTPUT > /dev/null 2>&1
    # rm -rf $TEMP > /dev/null 2>&1
fi

# write symbol table to OUTPUT and exit

if [[ $GENERATE_SYMBOL_TABLE -ne 0 ]];
then
    OUTPUT=${INPUT%%.m}.sym
    
    mas -s < $TEMP > $OUTPUT

    # abort if writing symbol table failed
    
    if [[ $? -ne 0 ]];
    then
	rm -rf $TEMP $OUTPUT > /dev/null 2>&1
	exit 1
    fi
    
    # rm -rf $TEMP > /dev/null 2>&1
fi

# generate OUTPUT by stripping .m suffix from INPUT and adding .class

OUTPUT=${INPUT%%.m}.class

# assemble, writing class file to OUTPUT

mas < $TEMP > $OUTPUT

# abort if assembler stage failed

if [[ $? -ne 0 ]];
then
    rm -rf $TEMP $OUTPUT > /dev/null 2>&1
    exit 1
fi

# cleanup and exit success

rm -rf $TEMP > /dev/null 2>&1
exit 0
