
#line 3 "scan.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 41
#define YY_END_OF_BUFFER 42
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[327] =
    {   0,
        0,    0,   42,   40,    2,    4,   40,   40,    1,   40,
       34,   37,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,    3,    0,   33,    1,   38,   38,   34,
       34,   37,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   18,    0,    0,    0,    0,    0,    0,
        0,    0,   39,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   18,    0,    0,    0,    0,    0,    0,
        0,   38,   38,   38,   34,    0,   36,    0,    0,    0,
        0,    0,    0,   13,    0,    0,    0,    0,    0,   24,

       28,   29,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   13,    0,    0,    0,    0,    0,    0,   24,   28,
       29,    0,    0,    0,   38,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   16,   17,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   16,   17,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   38,    0,   35,    0,    8,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    8,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   38,

        0,    0,   10,    0,   12,   14,    0,    0,    0,   25,
        0,   27,    0,   31,   32,    0,    0,   10,    0,   12,
       14,    0,    0,    0,    0,   25,    0,   27,    0,   31,
       32,   38,    0,    9,    0,    0,    0,    0,    0,    0,
       26,    0,    0,    9,    0,    0,    0,    0,    0,    0,
        0,   26,    0,   38,    0,    0,   15,    0,    0,    0,
        0,   30,    0,    0,   15,    0,    0,    0,    0,    0,
       30,   38,    0,   11,    0,    0,    0,    0,    0,    0,
       11,    0,    0,    0,    0,    0,    0,    6,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    5,    0,

        0,    7,    0,    0,    0,    0,   23,    7,    0,    0,
        0,    0,   23,   20,    0,    0,   22,   20,    0,    0,
       22,   19,   21,   19,   21,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    8,    5,    5,    5,    5,
        5,    5,    9,    5,    9,   10,    5,   11,   12,   11,
       11,   11,   11,   11,   11,   11,   11,   13,    5,    5,
        1,    5,    1,    1,   14,   15,   14,   14,   16,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
        5,    1,    5,    1,   17,    1,   18,   14,   19,   20,

       21,   22,   23,   24,   25,   14,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
       14,   14,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[40] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    3,    3,    3,
        3,    3,    3,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4
    } ;

static yyconst flex_int16_t yy_base[332] =
    {   0,
        0,   39,  871,  872,  872,  872,  867,  863,    0,  840,
       68,   71,   66,  843,   65,   67,   62,  836,  844,  828,
       59,  842,   91,   94,   98,  103,  119,  107,  130,  133,
      122,  139,  144,  872,  856,  872,    0,  114,  150,  126,
      152,  160,  168,  831,  830,  838,  823,  836,  829,  824,
      819,  818,  831,  814,  815,  796,  798,  800,  795,  131,
      171,  174,  177,  180,  183,  186,  189,  193,  204,  207,
      210,  214,  221,  217,  228,  235,  224,  239,  244,  247,
      254,  162,  197,  258,  269,  200,  232,  799,  786,  768,
      764,  766,  759,  762,  749,  739,  730,  731,  713,  238,

      872,  872,  715,  716,  696,  266,  275,  285,  288,  291,
      294,  300,  310,  313,  316,  322,  325,  328,  330,  333,
      347,  354,  358,  361,  280,  369,  697,  703,  679,  681,
      678,  667,  658,  645,  872,  872,  643,  632,  635,  636,
      620,  629,  616,  610,  371,  374,  377,  387,  380,  390,
      396,  399,  403,  406,  410,  415,  420,  427,  430,  433,
      436,  441,  446,  451,  319,  339,  584,  872,  585,  595,
      591,  577,  585,  568,  543,  528,  507,  516,  500,  510,
      492,  493,  459,  462,  465,  469,  472,  475,  488,  491,
      494,  497,  505,  508,  514,  517,  525,  528,  536,  533,

      497,  484,  872,  479,  872,  872,  468,  400,  456,  872,
      440,  872,  438,  872,  872,  540,  543,  550,  555,  558,
      563,  566,  583,  569,  572,  575,  579,  589,  596,  602,
      613,  481,  435,  872,  426,  430,  386,  365,  370,  358,
      872,  355,  616,  619,  622,  626,  629,  637,  640,  647,
      650,  661,  664,  592,  332,  321,  872,  312,  321,  286,
       69,  872,  667,  670,  674,  677,  680,  683,  687,  695,
      698,  610,  289,  872,  289,  289,  259,  249,  248,  706,
      709,  714,  717,  729,  732,  735,  738,  350,  241,  224,
      178,  142,  146,  124,  741,  744,  747,  754,  762,  765,

      771,  872,  126,  105,   99,   79,  872,  776,  780,  784,
      787,  796,  799,  872,   69,   67,  872,  802,  805,  808,
      811,  872,  872,  814,  825,  872,  838,  842,   86,  844,
      846
    } ;

static yyconst flex_int16_t yy_def[332] =
    {   0,
      326,  326,  326,  326,  326,  326,  326,  327,  328,  329,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  326,  327,  326,  328,  331,  331,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  331,  331,  331,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,

      326,  326,  326,  326,  326,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,   24,  330,
      330,  330,  330,  330,  331,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  331,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  331,

      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  331,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  331,  326,  326,  326,  326,  326,  326,
      326,  326,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  331,  326,  326,  326,  326,  326,  326,  326,  330,
      330,  330,  330,  330,  330,  330,  330,  331,  326,  326,
      326,  326,  326,  326,  330,  330,  330,  330,  330,  330,

      330,  326,  326,  326,  326,  326,  326,  330,  330,  330,
      330,  330,  330,  326,  326,  326,  326,  330,  330,  330,
      330,  326,  326,  330,  330,    0,  326,  326,  326,  326,
      326
    } ;

static yyconst flex_int16_t yy_nxt[912] =
    {   0,
        4,    5,    6,    7,    4,    8,    9,   10,    4,   11,
       12,   12,    4,    4,    4,    4,    4,   13,   14,   15,
        4,    4,   16,    4,   17,    4,    4,   18,   19,   20,
       21,    4,   22,    4,    4,    4,    4,    4,    4,    4,
        5,    6,    7,    4,    8,    9,   10,    4,   11,   12,
       12,    4,   23,   23,   23,   23,   24,   25,   26,   23,
       23,   27,   23,   28,   23,   23,   29,   30,   31,   32,
       23,   33,   23,   23,   23,   23,   23,   23,   40,   40,
       41,   42,   42,   53,   44,   49,   43,   51,   58,   38,
       54,   43,   45,  323,   59,  322,   52,  278,   46,   47,

       50,   62,   62,   63,   62,   62,   63,  279,   62,   62,
       63,  317,   64,   62,   62,   63,  316,   62,   62,   63,
       65,   68,  315,   69,   83,   83,   66,   67,   73,   62,
       62,   63,   62,   62,   63,   74,   40,   40,   70,   71,
       62,   62,   63,   62,   62,   63,  314,   75,   72,   62,
       62,   63,  104,   77,   62,   62,   63,   78,  307,   76,
       83,   83,   85,   85,   81,  105,  306,   84,   79,   41,
       42,   42,   83,   83,   80,   43,   86,  305,   87,   87,
       43,   62,   62,   63,   62,   62,   63,   62,   62,   63,
       62,   62,   63,   62,   62,   63,   62,   62,   63,   62,

       62,   63,  304,   62,   62,   63,  108,   83,   83,  106,
       87,   87,  107,  110,   62,   62,   63,   62,   62,   63,
       62,   62,   63,  109,   62,   62,   63,   62,   62,   63,
      111,   62,   62,   63,   62,   62,   63,  112,   62,   62,
       63,  115,   87,   87,  113,   62,   62,   63,  114,   62,
       62,   63,  117,  116,   62,   62,   63,   62,   62,   63,
      303,  119,  139,  118,   62,   62,   63,  302,   83,   83,
      140,  141,  294,  120,  121,  123,   62,   62,   63,   85,
       85,  122,  125,  293,  126,   62,   62,   63,  124,  126,
       83,   83,  146,  292,  145,   62,   62,   63,   62,   62,

       63,   62,   62,   63,   62,   62,   63,  291,  164,  149,
       62,   62,   63,  290,  150,  289,  151,  148,  277,  147,
       62,   62,   63,   62,   62,   63,   62,   62,   63,  166,
      166,  152,   62,   62,   63,   62,   62,   63,   62,   62,
       63,  276,  153,   62,   62,   63,  275,  154,   61,  166,
      166,  155,  157,  156,  158,  274,   61,   62,   62,   63,
       83,   83,  159,  160,   62,   62,   63,  273,   62,   62,
       63,   62,   62,   63,  262,  161,  162,  165,  261,  166,
      166,   62,   62,   63,   62,   62,   63,   62,   62,   63,
       62,   62,   63,  184,  260,  259,  163,   62,   62,   63,

       62,   62,   63,  258,  183,  187,   62,   62,   63,   62,
       62,   63,  185,   62,   62,   63,   62,   62,   63,  186,
       62,   62,   63,  190,  188,   62,   62,   63,  237,  192,
       62,   62,   63,  238,  189,  191,  239,   62,   62,   63,
       62,   62,   63,   62,   62,   63,   62,   62,   63,  257,
      195,   62,   62,   63,  193,  194,   62,   62,   63,  256,
      197,   83,   83,  255,  242,  200,  241,  196,  198,   62,
       62,   63,   62,   62,   63,   62,   62,   63,  199,   62,
       62,   63,   62,   62,   63,   62,   62,   63,  240,  218,
      219,   83,   83,  216,  236,  220,  235,  217,   62,  221,

       63,   62,   62,   63,   62,   62,   63,   62,   62,   63,
      254,  222,  234,  233,  223,   62,   62,   63,   62,   62,
       63,  215,  214,  224,   62,   62,   63,   62,   62,   63,
      213,  227,  212,  211,  225,   62,   62,   63,   62,   62,
       63,  210,  226,   83,   83,  229,   62,   62,   63,  228,
       62,   62,   63,   62,   62,   63,  243,  209,  230,  232,
       62,   62,   63,  208,  231,   62,   62,   63,   62,   62,
       63,  244,  245,   62,   62,   63,   62,   62,   63,   62,
       62,   63,   62,   62,   63,   62,   62,   63,  207,   62,
       62,   63,  246,   62,   62,   63,  206,  205,  250,   62,

       62,   63,   83,   83,  251,  252,   62,   62,   63,  204,
      272,  247,   62,   62,   63,  203,  248,  202,  201,  249,
       83,   83,  253,   62,   62,   63,   62,   62,   63,   62,
       62,   63,   62,   62,   63,  288,   62,   62,   63,   62,
       62,   63,  182,  181,  263,  265,  266,   62,   62,   63,
       62,   62,   63,  180,  179,  264,  178,   62,   62,   63,
       62,   62,   63,  177,  268,  269,  176,  267,  175,  174,
      270,   62,   62,   63,   62,   62,   63,   62,   62,   63,
       62,   62,   63,  271,   62,   62,   63,   62,   62,   63,
       62,   62,   63,   62,   62,   63,  173,   62,   62,   63,

      283,  172,  280,  171,  281,   62,   62,   63,   62,   62,
       63,  282,  285,  170,  169,  284,   62,   62,   63,   62,
       62,   63,  168,  286,   62,   62,   63,   62,   62,   63,
      167,  144,  295,  287,  143,  297,  142,  138,  296,   62,
       62,   63,   62,   62,  299,   62,   62,   63,   62,   62,
       63,   62,   62,   63,   62,   62,   63,   62,   62,   63,
      137,  136,  301,  298,   62,   62,   63,  308,  135,  300,
      134,  310,   62,   62,   63,   62,   62,   63,  133,  132,
      309,   62,   62,   63,  131,  312,   62,   62,   63,  311,
       62,   62,   63,  130,   62,   62,   63,   62,   62,   63,

      318,  319,  129,  128,  320,  313,   62,   62,   63,   62,
       62,   63,   62,   62,   63,   62,   62,   63,   62,   62,
       63,   62,   62,   63,   62,   62,   63,  127,  321,  103,
      102,  324,  101,  100,  325,   62,   62,   63,   35,   35,
       35,   35,   37,   99,   37,   37,   61,   61,   82,   82,
       98,   97,   96,   95,   94,   93,   92,   91,   90,   89,
       88,   36,   60,   57,   56,   55,   48,   39,   36,   34,
      326,    3,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,

      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326
    } ;

static yyconst flex_int16_t yy_chk[912] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,   11,   11,
       12,   12,   12,   17,   13,   15,   12,   16,   21,  329,
       17,   12,   13,  316,   21,  315,   16,  261,   13,   13,

       15,   23,   23,   23,   24,   24,   24,  261,   25,   25,
       25,  306,   24,   26,   26,   26,  305,   28,   28,   28,
       24,   25,  304,   26,   38,   38,   24,   24,   28,   27,
       27,   27,   31,   31,   31,   28,   40,   40,   26,   27,
       29,   29,   29,   30,   30,   30,  303,   29,   27,   32,
       32,   32,   60,   30,   33,   33,   33,   31,  294,   29,
       39,   39,   41,   41,   33,   60,  293,   39,   32,   42,
       42,   42,   82,   82,   32,   42,   43,  292,   43,   43,
       42,   61,   61,   61,   62,   62,   62,   63,   63,   63,
       64,   64,   64,   65,   65,   65,   66,   66,   66,   67,

       67,   67,  291,   68,   68,   68,   66,   83,   83,   64,
       86,   86,   65,   68,   69,   69,   69,   70,   70,   70,
       71,   71,   71,   67,   72,   72,   72,   74,   74,   74,
       69,   73,   73,   73,   77,   77,   77,   70,   75,   75,
       75,   73,   87,   87,   71,   76,   76,   76,   72,   78,
       78,   78,   75,   74,   79,   79,   79,   80,   80,   80,
      290,   77,  100,   76,   81,   81,   81,  289,   84,   84,
      100,  100,  279,   78,   79,   81,  106,  106,  106,   85,
       85,   80,   84,  278,   85,  107,  107,  107,   81,   85,
      125,  125,  107,  277,  106,  108,  108,  108,  109,  109,

      109,  110,  110,  110,  111,  111,  111,  276,  125,  110,
      112,  112,  112,  275,  111,  273,  112,  109,  260,  108,
      113,  113,  113,  114,  114,  114,  115,  115,  115,  165,
      165,  113,  116,  116,  116,  117,  117,  117,  118,  118,
      118,  259,  114,  120,  120,  120,  258,  115,  119,  166,
      166,  116,  118,  117,  119,  256,  119,  121,  121,  121,
      288,  288,  119,  119,  122,  122,  122,  255,  123,  123,
      123,  124,  124,  124,  242,  122,  123,  126,  240,  126,
      126,  145,  145,  145,  146,  146,  146,  147,  147,  147,
      149,  149,  149,  146,  239,  238,  124,  148,  148,  148,

      150,  150,  150,  237,  145,  149,  151,  151,  151,  152,
      152,  152,  147,  153,  153,  153,  154,  154,  154,  148,
      155,  155,  155,  152,  150,  156,  156,  156,  208,  156,
      157,  157,  157,  208,  151,  155,  208,  158,  158,  158,
      159,  159,  159,  160,  160,  160,  161,  161,  161,  236,
      159,  162,  162,  162,  157,  158,  163,  163,  163,  235,
      161,  164,  164,  233,  213,  164,  211,  160,  162,  183,
      183,  183,  184,  184,  184,  185,  185,  185,  163,  186,
      186,  186,  187,  187,  187,  188,  188,  188,  209,  186,
      187,  232,  232,  183,  207,  188,  204,  185,  189,  189,

      189,  190,  190,  190,  191,  191,  191,  192,  192,  192,
      232,  190,  202,  201,  191,  193,  193,  193,  194,  194,
      194,  182,  181,  192,  195,  195,  195,  196,  196,  196,
      180,  195,  179,  178,  193,  197,  197,  197,  198,  198,
      198,  177,  194,  200,  200,  197,  199,  199,  199,  196,
      216,  216,  216,  217,  217,  217,  216,  176,  198,  200,
      218,  218,  218,  175,  199,  219,  219,  219,  220,  220,
      220,  217,  219,  221,  221,  221,  222,  222,  222,  224,
      224,  224,  225,  225,  225,  226,  226,  226,  174,  227,
      227,  227,  222,  223,  223,  223,  173,  172,  224,  228,

      228,  228,  254,  254,  225,  227,  229,  229,  229,  171,
      254,  223,  230,  230,  230,  170,  223,  169,  167,  223,
      272,  272,  229,  231,  231,  231,  243,  243,  243,  244,
      244,  244,  245,  245,  245,  272,  246,  246,  246,  247,
      247,  247,  144,  143,  243,  246,  247,  248,  248,  248,
      249,  249,  249,  142,  141,  245,  140,  250,  250,  250,
      251,  251,  251,  139,  249,  250,  138,  248,  137,  134,
      251,  252,  252,  252,  253,  253,  253,  263,  263,  263,
      264,  264,  264,  253,  265,  265,  265,  266,  266,  266,
      267,  267,  267,  268,  268,  268,  133,  269,  269,  269,

      267,  132,  263,  131,  264,  270,  270,  270,  271,  271,
      271,  266,  269,  130,  129,  268,  280,  280,  280,  281,
      281,  281,  128,  270,  282,  282,  282,  283,  283,  283,
      127,  105,  280,  270,  104,  283,  103,   99,  282,  284,
      284,  284,  285,  285,  285,  286,  286,  286,  287,  287,
      287,  295,  295,  295,  296,  296,  296,  297,  297,  297,
       98,   97,  287,  284,  298,  298,  298,  295,   96,  286,
       95,  297,  299,  299,  299,  300,  300,  300,   94,   93,
      296,  301,  301,  301,   92,  300,  308,  308,  308,  298,
      309,  309,  309,   91,  310,  310,  310,  311,  311,  311,

      309,  310,   90,   89,  311,  301,  312,  312,  312,  313,
      313,  313,  318,  318,  318,  319,  319,  319,  320,  320,
      320,  321,  321,  321,  324,  324,  324,   88,  312,   59,
       58,  319,   57,   56,  320,  325,  325,  325,  327,  327,
      327,  327,  328,   55,  328,  328,  330,  330,  331,  331,
       54,   53,   52,   51,   50,   49,   48,   47,   46,   45,
       44,   35,   22,   20,   19,   18,   14,   10,    8,    7,
        3,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,

      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scan.l"
#line 2 "scan.l"

/* Niels Widger
 * Time-stamp: <23 Dec 2010 at 20:58:46 by nwidger on macros.local>
 */

#ifdef HAVE_CONFIG_H
# include <config.h>
#endif

#include <inttypes.h>
#include <stdio.h>	
#include <stdlib.h>
#include <string.h>
#include <errno.h>

#include <constants.h>

#include "parse.h"

/* local prototypes */
static unsigned long a2int(char *);
static float a2float(char *tptr);

/* need to use global string pool from main.C */
extern int yyparse();

/* scanner tracks the current line number */
int line = 1;
int get_current_source_line_number();

/* following supports the stand-alone scanner program: lexdbg */
#ifdef DEBUG
#define token(x) (display_token((char *) # x),  x)
YYSTYPE yylval;
int display_token (char *);

#else

#define token(x) x

#endif

#define YY_NO_INPUT 1
#line 803 "scan.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 54 "scan.l"


#line 989 "scan.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 327 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 872 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 56 "scan.l"
{
			   /* do nothing: comments discarded */
			 }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 60 "scan.l"
{
                           /* do nothing: whitespace discarded */
                         }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 64 "scan.l"
{
                           /* just advance the line number then discard newline */
                           line += 1;
			 }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 69 "scan.l"
{
                           /* just advance the line number then discard newline */
                           line += 1;
                         }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 74 "scan.l"
{
			   yytext[strlen(yytext)-1] = '\0';
			   return token(MAINBLOCKLABEL);
			 }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 79 "scan.l"
{
			   yytext++;
			   return token(MAINBLOCKVARIABLE);
			 }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 84 "scan.l"
{
			   return token(ACONST_NULL);
			 }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 88 "scan.l"
{
			   return token(ALOAD);
			 }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 92 "scan.l"
{
			   return token(ARETURN);
			 }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 96 "scan.l"
{
			   return token(ASTORE);
			 }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 100 "scan.l"
{
			   return token(CHECKCAST);
			 }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 104 "scan.l"
{
			   return token(DELETE);
			 }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 108 "scan.l"
{
			   return token(DUP);
			 }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 112 "scan.l"
{
			   return token(DUP_X1);
			 }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 116 "scan.l"
{
			   return token(GETFIELD);
			 }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 120 "scan.l"
{
			   return token(GOTO);
			 }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 124 "scan.l"
{
			   return token(IFEQ);
			 }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 128 "scan.l"
{
			   return token(IN);
			 }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 132 "scan.l"
{
			   return token(INVOKESPECIAL);
			 }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 136 "scan.l"
{
			   return token(INVOKENATIVE);
			 }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 140 "scan.l"
{
			   return token(INVOKEVIRTUAL);
			 }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 144 "scan.l"
{
			   return token(MONITORENTER);
			 }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 148 "scan.l"
{
			   return token(MONITOREXIT);
			 }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 152 "scan.l"
{
			   return token(NEW);
			 }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 156 "scan.l"
{
			   return token(NEWINT);
			 }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 160 "scan.l"
{
			   return token(NEWREAL);
			 }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 164 "scan.l"
{
			   return token(NEWSTR);
			 }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 168 "scan.l"
{
			   return token(OUT);
			 }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 172 "scan.l"
{
			   return token(POP);
			 }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 176 "scan.l"
{
			   return token(PUTFIELD);
			 }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 180 "scan.l"
{
			   return token(REFCMP);
			 }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 184 "scan.l"
{
			   return token(RETURN);
			 }
	YY_BREAK
case 33:
/* rule 33 can match eol */
YY_RULE_SETUP
#line 188 "scan.l"
{
			   yytext[strlen(yytext)-1] = '\0';
			   yytext++;
			   return token(STRING_LITERAL);
			 }			 
	YY_BREAK
case 34:
#line 195 "scan.l"
case 35:
#line 196 "scan.l"
case 36:
YY_RULE_SETUP
#line 196 "scan.l"
{
                           yylval.float_value = a2float(yytext);
                           return token(FLOAT_LITERAL);
                         }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 201 "scan.l"
{
			   yylval.value = a2int(yytext);
                           return token(INTEGER_LITERAL);
                         }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 206 "scan.l"
{
			   yytext++;
			   return token(VARIABLE);
			 }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 211 "scan.l"
{
			   yytext[strlen(yytext)-1] = '\0';
			   return token(LABEL);
			 }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 216 "scan.l"
{
                           return token(BAD);
                         }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 220 "scan.l"
ECHO;
	YY_BREAK
#line 1361 "scan.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 327 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 327 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 326);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 220 "scan.l"



int yywrap(void) {
  return 1;
}

/*
 * Convert from ascii hex to an integer.
 */
static unsigned long a2int(char *tptr)
{
  uint64_t uint64_t_tmp;
  uint32_t uint32_t_tmp;
  uint64_t uint64_t_tmp2;  

  // errno used to detect overflow of long long
  errno = 0;
  uint64_t_tmp = strtoull(tptr, NULL, 0);
  if (errno)
  {
    fprintf(stderr, "mas: integer literal too large\n");
    return 0;
  }

  // check now if value will fit in uint32_t
  uint32_t_tmp = uint64_t_tmp;
  uint64_t_tmp2 = uint32_t_tmp;
  if (uint32_t_tmp != uint64_t_tmp2)
  {
    fprintf(stderr, "mas: integer literal too large\n");
    return 0;
  }

  if (uint32_t_tmp < INTEGER_MIN_INTEGER) {
    fprintf(stderr, "mas: integer literal too small\n");
    return 0;
  }

  if (uint32_t_tmp > INTEGER_MAX_INTEGER) {
    fprintf(stderr, "mas: integer literal too large\n");
    return 0;
  }

  return uint32_t_tmp;
}


/*
 * Convert from ascii hex to a float.
 */
static float a2float(char *tptr)
{
  float float_tmp;

  // errno used to detect overflow/underflow of float
  errno = 0;
  float_tmp = strtof(tptr, NULL);
  if (errno)
  {
    if (errno == ERANGE)
    {
      fprintf(stderr, "mas: float literal out of range\n");
    }

    if (errno == EINVAL)
    {
      fprintf(stderr, "mas: float literal is invalid\n");
    }
    
    return 0;
  }

  return float_tmp;
}

/* provide the AST routines access to the line number */
int get_current_source_line_number()
{
  return line;
}

/* following supports the stand-alone scanner program: lexdbg */
#ifdef DEBUG

int main()
{
  while (yylex());

  return 0;
}

int display_token(char *p)
{
  fprintf(stderr, "%s is %s\n", p, yytext);
  return 1;
}
#endif


