/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 37
#define YY_END_OF_BUFFER 38
static yyconst short int yy_accept[309] =
    {   0,
        0,    0,   38,   36,    2,    4,   36,   36,    1,   36,
       33,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,    3,    0,   32,    1,   34,   34,   33,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   18,
        0,    0,    0,    0,    0,    0,    0,    0,   35,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   18,
        0,    0,    0,    0,    0,    0,    0,   34,   34,   34,
        0,    0,    0,    0,    0,    0,   13,    0,    0,    0,
        0,    0,   24,   27,   28,    0,    0,    0,    0,    0,

        0,    0,    0,    0,   13,    0,    0,    0,    0,    0,
        0,   24,   27,   28,    0,    0,    0,   34,    0,    0,
        0,    0,    0,    0,    0,    0,   16,   17,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   16,   17,    0,    0,    0,    0,    0,
        0,    0,    0,   34,    0,    8,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        8,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   34,    0,    0,   10,    0,
       12,   14,    0,    0,    0,   25,   26,    0,   30,   31,

        0,    0,   10,    0,   12,   14,    0,    0,    0,    0,
       25,   26,    0,   30,   31,   34,    0,    9,    0,    0,
        0,    0,    0,    0,    0,    0,    9,    0,    0,    0,
        0,    0,    0,    0,    0,   34,    0,    0,   15,    0,
        0,    0,    0,   29,    0,    0,   15,    0,    0,    0,
        0,    0,   29,   34,    0,   11,    0,    0,    0,    0,
        0,    0,   11,    0,    0,    0,    0,    0,    0,    6,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        5,    0,    0,    7,    0,    0,    0,    0,   23,    7,
        0,    0,    0,    0,   23,   20,    0,    0,   22,   20,

        0,    0,   22,   19,   21,   19,   21,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    8,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    9,   10,    9,
        9,    9,    9,    9,    9,    9,    9,   11,    5,    5,
        1,    5,    1,    1,   12,   13,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
        5,    1,    5,    1,   14,    1,   15,   12,   16,   17,

       18,   19,   20,   21,   22,   12,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   35,   36,
       12,   12,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[37] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    3,    3,    3,
        3,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4
    } ;

static yyconst short int yy_base[314] =
    {   0,
        0,   36,  812,  813,  813,  813,  808,  804,    0,  778,
       64,   59,  775,   58,   59,   59,  768,  775,  759,   54,
      772,   83,   86,   90,   94,   97,  109,  121,  128,  112,
      131,  141,  813,  780,  813,    0,   70,  134,  104,  753,
      749,  756,  738,  749,  742,  735,  725,  724,  732,  710,
      708,  697,  697,  695,  684,  115,  144,  151,  156,  159,
      162,  165,  168,  181,  171,  187,  192,  195,  198,  201,
      208,  211,  222,  229,  232,  235,  239,  116,  147,  204,
      688,  697,  675,  679,  689,  686,  678,  669,  660,  655,
      651,  642,  162,  813,  813,  639,  630,  612,  242,  254,

      245,  263,  269,  273,  278,  284,  287,  290,  295,  298,
      301,  306,  316,  320,  323,  329,  337,  326,  608,  618,
      596,  598,  602,  582,  574,  575,  813,  813,  573,  559,
      564,  541,  550,  542,  536,  340,  344,  347,  353,  356,
      363,  366,  375,  378,  381,  389,  394,  399,  404,  407,
      410,  413,  416,  424,  529,  813,  530,  518,  519,  505,
      508,  498,  492,  477,  451,  452,  449,  438,  438,  431,
      434,  438,  441,  444,  447,  460,  463,  466,  469,  476,
      479,  485,  488,  491,  498,  372,  448,  435,  813,  421,
      813,  813,  411,  287,  399,  813,  813,  404,  813,  813,

      503,  511,  516,  519,  522,  529,  532,  548,  535,  538,
      541,  544,  554,  560,  566,  384,  380,  813,  370,  361,
      354,  340,  338,  341,  327,  554,  555,  561,  567,  568,
      577,  578,  590,  589,  596,  178,  310,  309,  813,  288,
      284,  256,   62,  813,  600,  606,  610,  616,  625,  623,
      629,  635,  636,  482,  257,  813,  254,  259,  238,  234,
      240,  648,  642,  655,  649,  659,  608,  685,  688,  219,
      235,  213,  214,  201,  207,  191,  691,  677,  687,  693,
      694,  704,  705,  813,  167,  148,  118,   99,  813,  714,
      715,  727,  728,  721,  734,  813,   85,   60,  813,  738,

      747,  751,  753,  813,  813,  757,  763,  813,  797,  801,
       78,  803,  805
    } ;

static yyconst short int yy_def[314] =
    {   0,
      308,  308,  308,  308,  308,  308,  308,  309,  310,  311,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  308,  309,  308,  310,  313,  313,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  313,  313,  313,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  312,  312,

      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  313,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  313,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  313,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,

      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  313,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  313,  308,  308,  308,  308,
      308,  308,  308,  308,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  313,  308,  308,  308,  308,  308,  308,
      308,  208,  208,  208,  208,  208,  312,  312,  312,  313,
      308,  308,  308,  308,  308,  308,  312,  208,  208,  208,
      208,  208,  208,  308,  308,  308,  308,  308,  308,  208,
      208,  208,  208,  208,  208,  308,  308,  308,  308,  208,

      208,  208,  208,  308,  308,  208,  208,    0,  308,  308,
      308,  308,  308
    } ;

static yyconst short int yy_nxt[850] =
    {   0,
        4,    5,    6,    7,    4,    8,    9,   10,   11,   11,
        4,    4,    4,    4,   12,   13,   14,    4,    4,   15,
        4,   16,    4,    4,   17,   18,   19,   20,    4,   21,
        4,    4,    4,    4,    4,    4,    4,    5,    6,    7,
        4,    8,    9,   10,   11,   11,    4,   22,   22,   22,
       23,   24,   25,   22,   22,   26,   22,   27,   22,   22,
       28,   29,   30,   31,   22,   32,   22,   22,   22,   22,
       22,   22,   39,   39,   40,   45,   47,   49,   79,   79,
       54,   37,   41,  305,   50,   48,   55,  260,   42,   43,
       46,   58,   58,   59,   58,   58,   59,  261,   58,   58,

       59,   60,   58,   58,   59,   58,   58,   59,  304,   61,
       64,   65,   39,   39,   67,   62,   63,   58,   58,   59,
       58,   58,   59,   68,   79,   79,   66,   69,  299,   58,
       58,   59,  298,   97,   70,   71,   58,   58,   59,   58,
       58,   59,   79,   79,   74,   73,   98,   72,   80,   58,
       58,   59,   58,   58,   59,   79,   79,   75,   77,   58,
       58,   59,  297,   76,   58,   58,   59,   58,   58,   59,
       58,   58,   59,   58,   58,   59,   58,   58,   59,   58,
       58,   59,  101,  131,  296,   99,   79,   79,  100,   58,
       58,   59,  132,  254,  104,   58,   58,   59,  103,  102,

       58,   58,   59,   58,   58,   59,   58,   58,   59,   58,
       58,   59,   79,   79,  105,  108,   58,   58,   59,   58,
       58,   59,  289,  106,  288,  118,  107,   79,   79,  110,
       58,   58,   59,  287,  109,  286,  111,   58,   58,   59,
       58,   58,   59,   58,   58,   59,  285,   58,   58,   59,
       58,   58,   59,   58,   58,   59,  112,  116,  284,  114,
      113,  276,   58,   58,   59,  275,  115,  136,  137,  274,
      117,   58,   58,   59,  273,  272,  138,   58,   58,   59,
      271,   58,   58,   59,  140,  259,   58,   58,   59,  139,
      141,  142,   58,   58,   59,   58,   58,   59,   58,   58,

       59,  258,  143,   58,   58,   59,   58,   58,   59,   58,
       58,   59,  221,  144,   58,   58,   59,  222,  145,  257,
      223,  146,  148,  147,   58,   58,   59,  149,   58,   58,
       59,   58,   58,   59,   79,   79,  150,   58,   58,   59,
      256,  151,  255,  244,  152,   58,   58,   59,   58,   58,
       59,  154,   58,   58,   59,   58,   58,   59,  243,  242,
      171,   58,   58,   59,   58,   58,   59,  241,  240,  153,
      170,   58,   58,   59,   58,   58,   59,  239,  174,  172,
       79,   79,  173,   58,   58,   59,   58,   58,   59,   58,
       58,   59,   79,   79,  175,  216,  177,   58,   58,   59,

      238,  176,   58,   58,   59,  237,  179,   58,   58,   59,
      236,  178,   58,   58,   59,   58,   58,   59,   58,   58,
       59,   58,   58,   59,   58,   58,   59,  225,  224,  181,
      180,  183,   79,   79,  220,  219,  186,  184,  182,   58,
       58,   59,   58,   58,   59,  185,   58,   58,   59,   58,
       58,   59,   58,   58,   59,   58,   58,   59,  203,  204,
      218,  217,  201,  200,  205,  199,  198,  202,   58,  206,
       59,   58,   58,   59,   58,   58,   59,   58,   58,   59,
      207,  197,  196,  208,   58,   58,   59,   58,   58,   59,
       79,   79,  209,   58,   58,   59,   58,   58,   59,   58,

       58,   59,  210,  195,  270,  213,   58,   58,   59,  194,
      211,   58,   58,   59,  212,  193,  226,  192,  214,   58,
       58,   59,  191,  215,   58,   58,   59,   58,   58,   59,
       58,   58,   59,  228,  190,  189,  227,   58,   58,   59,
       58,   58,   59,   58,   58,   59,   58,   58,   59,   58,
       58,   59,   58,   58,   59,  229,   58,   58,   59,  188,
      187,  233,   58,   58,   59,  169,  168,  234,   58,   58,
       59,  167,  166,  230,   58,   58,   59,  235,  231,  245,
       57,  232,  248,  247,   57,   57,   57,   57,   57,  165,
      164,  246,   57,   57,   57,  163,  162,   57,   57,  250,

       57,   57,   57,   57,  249,  251,  252,   57,   57,  161,
       57,   57,  253,  160,   57,   57,   58,   58,  281,   57,
       57,   57,   57,   57,  159,   57,   57,  158,  157,   57,
       57,   57,  262,   57,  156,   57,   57,  263,  155,   57,
       57,   57,  265,   57,  135,  134,   57,  264,   57,   57,
       57,  267,  266,   57,   57,   57,   57,  133,   57,   57,
      268,   57,   57,  130,  279,   57,   57,   57,   57,   57,
      269,  277,   57,   57,   57,   57,  278,  129,   57,   57,
       57,   57,   57,  128,   57,   57,  127,  126,   57,   57,
      280,  125,   57,   58,   58,   59,   58,   58,   59,   58,

       58,   59,   57,  124,  123,  122,  121,   57,  292,  283,
      291,  120,   57,  119,  290,   96,  282,   57,   57,   57,
       57,  294,   95,   57,   57,  293,   57,   57,   94,   57,
       57,   93,  300,   92,   57,   57,  295,   57,   57,   57,
       57,  301,  302,   91,   57,   57,   57,   57,   57,   90,
      303,   57,   57,   57,   57,   89,   88,   57,   57,   57,
       57,   57,   87,   57,   57,   86,   85,   57,   57,   84,
      306,   57,   57,   83,  307,   82,   57,   57,   57,   81,
       57,   57,   57,   57,   57,   35,   57,   57,   57,   56,
       57,   53,   52,   57,   51,   44,   57,   34,   34,   34,

       34,   36,   38,   36,   36,   57,   57,   78,   78,   35,
       33,  308,    3,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308
    } ;

static yyconst short int yy_chk[850] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,   11,   11,   12,   14,   15,   16,   37,   37,
       20,  311,   12,  298,   16,   15,   20,  243,   12,   12,
       14,   22,   22,   22,   23,   23,   23,  243,   24,   24,

       24,   23,   25,   25,   25,   26,   26,   26,  297,   23,
       24,   25,   39,   39,   26,   23,   23,   27,   27,   27,
       30,   30,   30,   26,   78,   78,   25,   27,  288,   28,
       28,   28,  287,   56,   27,   28,   29,   29,   29,   31,
       31,   31,   38,   38,   30,   29,   56,   28,   38,   32,
       32,   32,   57,   57,   57,   79,   79,   31,   32,   58,
       58,   58,  286,   31,   59,   59,   59,   60,   60,   60,
       61,   61,   61,   62,   62,   62,   63,   63,   63,   65,
       65,   65,   62,   93,  285,   60,  236,  236,   61,   64,
       64,   64,   93,  236,   65,   66,   66,   66,   64,   63,

       67,   67,   67,   68,   68,   68,   69,   69,   69,   70,
       70,   70,   80,   80,   66,   69,   71,   71,   71,   72,
       72,   72,  276,   67,  275,   80,   68,  270,  270,   71,
       73,   73,   73,  274,   70,  273,   72,   74,   74,   74,
       75,   75,   75,   76,   76,   76,  272,   77,   77,   77,
       99,   99,   99,  101,  101,  101,   73,   77,  271,   75,
       74,  261,  100,  100,  100,  260,   76,   99,  100,  259,
       77,  102,  102,  102,  258,  257,  101,  103,  103,  103,
      255,  104,  104,  104,  103,  242,  105,  105,  105,  102,
      104,  105,  106,  106,  106,  107,  107,  107,  108,  108,

      108,  241,  106,  109,  109,  109,  110,  110,  110,  111,
      111,  111,  194,  107,  112,  112,  112,  194,  108,  240,
      194,  109,  111,  110,  113,  113,  113,  112,  114,  114,
      114,  115,  115,  115,  118,  118,  112,  116,  116,  116,
      238,  115,  237,  225,  116,  117,  117,  117,  136,  136,
      136,  118,  137,  137,  137,  138,  138,  138,  224,  223,
      137,  139,  139,  139,  140,  140,  140,  222,  221,  117,
      136,  141,  141,  141,  142,  142,  142,  220,  140,  138,
      186,  186,  139,  143,  143,  143,  144,  144,  144,  145,
      145,  145,  216,  216,  141,  186,  143,  146,  146,  146,

      219,  142,  147,  147,  147,  217,  147,  148,  148,  148,
      216,  146,  149,  149,  149,  150,  150,  150,  151,  151,
      151,  152,  152,  152,  153,  153,  153,  198,  195,  149,
      148,  151,  154,  154,  193,  190,  154,  152,  150,  170,
      170,  170,  171,  171,  171,  153,  172,  172,  172,  173,
      173,  173,  174,  174,  174,  175,  175,  175,  173,  174,
      188,  187,  170,  169,  175,  168,  167,  172,  176,  176,
      176,  177,  177,  177,  178,  178,  178,  179,  179,  179,
      177,  166,  165,  178,  180,  180,  180,  181,  181,  181,
      254,  254,  179,  182,  182,  182,  183,  183,  183,  184,

      184,  184,  180,  164,  254,  183,  185,  185,  185,  163,
      181,  201,  201,  201,  182,  162,  201,  161,  184,  202,
      202,  202,  160,  185,  203,  203,  203,  204,  204,  204,
      205,  205,  205,  204,  159,  158,  202,  206,  206,  206,
      207,  207,  207,  209,  209,  209,  210,  210,  210,  211,
      211,  211,  212,  212,  212,  207,  208,  208,  208,  157,
      155,  209,  213,  213,  213,  135,  134,  210,  214,  214,
      214,  133,  132,  208,  215,  215,  215,  213,  208,  226,
      227,  208,  230,  229,  226,  227,  228,  226,  227,  131,
      130,  228,  229,  230,  228,  129,  126,  229,  230,  232,

      229,  230,  231,  232,  231,  233,  234,  231,  232,  125,
      231,  232,  235,  124,  234,  233,  267,  267,  267,  234,
      233,  235,  234,  233,  123,  245,  235,  122,  121,  235,
      245,  246,  245,  245,  120,  247,  246,  246,  119,  246,
      247,  248,  249,  247,   98,   97,  248,  248,  250,  248,
      249,  251,  250,  250,  251,  249,  250,   96,  249,  251,
      252,  253,  251,   92,  265,  252,  253,  263,  252,  253,
      252,  262,  263,  262,  265,  263,  264,   91,  262,  265,
      264,  262,  265,   90,  266,  264,   89,   88,  264,  266,
      266,   87,  266,  268,  268,  268,  269,  269,  269,  277,

      277,  277,  278,   86,   85,   84,   83,  278,  279,  269,
      278,   82,  279,   81,  277,   55,  268,  279,  280,  281,
      279,  282,   54,  280,  281,  280,  280,  281,   53,  282,
      283,   52,  291,   51,  282,  283,  283,  282,  283,  290,
      291,  292,  293,   50,  290,  291,  294,  290,  291,   49,
      294,  294,  292,  293,  294,   48,   47,  292,  293,  295,
      292,  293,   46,  300,  295,   45,   44,  295,  300,   43,
      301,  300,  301,   42,  302,   41,  302,  301,  303,   40,
      301,  302,  306,  303,  302,   34,  303,  306,  307,   21,
      306,   19,   18,  307,   17,   13,  307,  309,  309,  309,

      309,  310,   10,  310,  310,  312,  312,  313,  313,    8,
        7,    3,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scan.l"
#define INITIAL 0
#line 2 "scan.l"

/* Niels Widger
 * Time-stamp: <16 Nov 2010 at 21:05:46 by nwidger on macros.local>
 */

#ifdef HAVE_CONFIG_H
# include <config.h>
#endif

#include <inttypes.h>
#include <stdio.h>	
#include <stdlib.h>
#include <string.h>
#include <errno.h>

#include <constants.h>

#include "parse.h"

/* local prototypes */
static unsigned long a2int(char *);

/* need to use global string pool from main.C */
extern int yyparse();

/* scanner tracks the current line number */
int line = 1;
int get_current_source_line_number();

/* following supports the stand-alone scanner program: lexdbg */
#ifdef DEBUG
#define token(x) (display_token((char *) # x),  x)
YYSTYPE yylval;
int display_token (char *);

#else

#define token(x) x

#endif

#define YY_NO_INPUT 1
#define YY_NO_UNPUT 1
#line 695 "scan.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 53 "scan.l"


#line 852 "scan.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 309 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 813 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 55 "scan.l"
{
			   /* do nothing: comments discarded */
			 }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 59 "scan.l"
{
                           /* do nothing: whitespace discarded */
                         }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 63 "scan.l"
{
                           /* just advance the line number then discard newline */
                           line += 1;
			 }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 68 "scan.l"
{
                           /* just advance the line number then discard newline */
                           line += 1;
                         }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 73 "scan.l"
{
			   yytext[strlen(yytext)-1] = '\0';
			   return token(MAINBLOCKLABEL);
			 }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 78 "scan.l"
{
			   yytext++;
			   return token(MAINBLOCKVARIABLE);
			 }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 83 "scan.l"
{
			   return token(ACONST_NULL);
			 }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 87 "scan.l"
{
			   return token(ALOAD);
			 }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 91 "scan.l"
{
			   return token(ARETURN);
			 }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 95 "scan.l"
{
			   return token(ASTORE);
			 }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 99 "scan.l"
{
			   return token(CHECKCAST);
			 }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 103 "scan.l"
{
			   return token(DELETE);
			 }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 107 "scan.l"
{
			   return token(DUP);
			 }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 111 "scan.l"
{
			   return token(DUP_X1);
			 }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 115 "scan.l"
{
			   return token(GETFIELD);
			 }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 119 "scan.l"
{
			   return token(GOTO);
			 }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 123 "scan.l"
{
			   return token(IFEQ);
			 }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 127 "scan.l"
{
			   return token(IN);
			 }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 131 "scan.l"
{
			   return token(INVOKESPECIAL);
			 }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 135 "scan.l"
{
			   return token(INVOKENATIVE);
			 }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 139 "scan.l"
{
			   return token(INVOKEVIRTUAL);
			 }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 143 "scan.l"
{
			   return token(MONITORENTER);
			 }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 147 "scan.l"
{
			   return token(MONITOREXIT);
			 }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 151 "scan.l"
{
			   return token(NEW);
			 }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 155 "scan.l"
{
			   return token(NEWINT);
			 }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 159 "scan.l"
{
			   return token(NEWSTR);
			 }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 163 "scan.l"
{
			   return token(OUT);
			 }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 167 "scan.l"
{
			   return token(POP);
			 }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 171 "scan.l"
{
			   return token(PUTFIELD);
			 }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 175 "scan.l"
{
			   return token(REFCMP);
			 }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 179 "scan.l"
{
			   return token(RETURN);
			 }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 183 "scan.l"
{
			   yytext[strlen(yytext)-1] = '\0';
			   yytext++;
			   return token(STRING_LITERAL);
			 }			 
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 189 "scan.l"
{
			   yylval.value = a2int(yytext);
                           return token(INTEGER_LITERAL);
                         }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 194 "scan.l"
{
			   yytext++;
			   return token(VARIABLE);
			 }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 199 "scan.l"
{
			   yytext[strlen(yytext)-1] = '\0';
			   return token(LABEL);
			 }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 204 "scan.l"
{
                           return token(BAD);
                         }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 208 "scan.l"
ECHO;
	YY_BREAK
#line 1202 "scan.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 309 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 309 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 308);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 208 "scan.l"


int yywrap(void) {
  return 1;
}

/*
 * Convert from ascii hex to an integer.
 */
static unsigned long a2int(char *tptr)
{
  uint64_t uint64_t_tmp;
  uint32_t uint32_t_tmp;
  uint64_t uint64_t_tmp2;  

  // errno used to detect overflow of long long
  errno = 0;
  uint64_t_tmp = strtoull(tptr, NULL, 0);
  if (errno)
  {
    fprintf(stderr, "mas: integer literal too large\n");
    return 0;
  }

  // check now if value will fit in uint32_t
  uint32_t_tmp = uint64_t_tmp;
  uint64_t_tmp2 = uint32_t_tmp;
  if (uint32_t_tmp != uint64_t_tmp2)
  {
    fprintf(stderr, "mas: integer literal too large\n");
    return 0;
  }

  if (uint32_t_tmp < INTEGER_MIN_INTEGER) {
    fprintf(stderr, "mas: integer literal too small\n");
    return 0;
  }

  if (uint32_t_tmp > INTEGER_MAX_INTEGER) {
    fprintf(stderr, "mas: integer literal too large\n");
    return 0;
  }

  return uint32_t_tmp;
}

/* provide the AST routines access to the line number */
int get_current_source_line_number()
{
  return line;
}

/* following supports the stand-alone scanner program: lexdbg */
#ifdef DEBUG

int main()
{
  while (yylex());

  return 0;
}

int display_token(char *p)
{
  fprintf(stderr, "%s is %s\n", p, yytext);
  return 1;
}
#endif

